#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER "$POSTGRES_APP_USERNAME" WITH PASSWORD '$POSTGRES_APP_PASSWORD';
  GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_APP_USERNAME";

  GRANT USAGE ON SCHEMA public TO "$POSTGRES_APP_USERNAME";
  GRANT CREATE ON SCHEMA public TO "$POSTGRES_APP_USERNAME";
EOSQL
